<?php
require ('../config/db.php');
require_once ('../controllers/emailControl.php');
############# IF PIGGY WALLET ONE (1) #######################
if(isset($_POST['piggy1btn'])){

  // DECLADE VARIABLES
  $amount = mysqli_real_escape_string($conn, $_POST['amount1']);

  $ch = curl_init();

  curl_setopt($ch, CURLOPT_URL, 'https://api.paystack.co/plan');
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_POST, 1);
  curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"name\": \"Piggy Wallat One (1)\", \"description\": \"Piggy Wallet 1 is 30 days saver this (works like Ajor, Akawo or Esusu,\", \"interval\": \"monthly\", \"amount\": $amount}");

  $headers = array();
  $headers[] = 'Authorization: Bearer sk_test_f89bb31f1bda1cdb1f77d255987843b82f1a8e56';
  $headers[] = 'Content-Type: application/json';
  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

  $result = curl_exec($ch);

  //print $data->data->plan_code;
  if ($result) {

    $plandata = json_decode($result);
    $plan_code = $plandata->data->plan_code;
    header('Location: ?success=plancreated&planCode='.$plan_code);

  }
  //   foreach ($json_output['orders'] as $billing_details) {
  // echo "<b>Name:</b><br>$billing_details['firstname'] $billing_details['lastname']<br>";}
  if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
  }
  curl_close($ch);

}

// function createSub($planCode){
//
//   // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
//   $ch = curl_init();
//
//   curl_setopt($ch, CURLOPT_URL, 'https://api.paystack.co/subscription');
//   curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
//   curl_setopt($ch, CURLOPT_POST, 1);
//   curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"customer\": \"CUS_5kgw5gs7z00ebck\", \"plan\": \"PLN_oguokulcmdr5pjn\"}");
//
//   $headers = array();
//   $headers[] = 'Authorization: Bearer sk_test_f89bb31f1bda1cdb1f77d255987843b82f1a8e56';
//   $headers[] = 'Content-Type: application/json';
//   curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
//
//   $result = curl_exec($ch);
//   if($result){
//     $subdata = json_decode($result);
//     $sub_code = $subdata->data->subscription_code;
//     header('Location: ?success=subcreated&subCode='.$subscription_code);
//   }
//   if (curl_errno($ch)) {
//     echo 'Error:' . curl_error($ch);
//   }
//   curl_close($ch);
// }
